class DataManager {
    constructor() {
        this.useApi = localStorage.getItem('adam_live_mode') === 'true'; // Controlled by UI toggle
        this.apiBase = '/api';
        this.staticBase = 'data/ui_data.json';
        this.data = null;
    }

    async init() {
        try {
            await this.fetchData();
        } catch (e) {
            console.warn("Data fetch failed, falling back to mock.", e);
            // Fallback to window.MOCK_DATA if available (generated by script)
            if (window.MOCK_DATA) {
                this.data = window.MOCK_DATA;
                console.log("Loaded data from window.MOCK_DATA");
            } else {
                this.data = this.getEmptyState();
            }
        }
    }

    async fetchData() {
        if (this.useApi) {
            console.log("Attempting LIVE API connection...");
            try {
                // Try a simple health check or fetch
                const controller = new AbortController();
                const timeoutId = setTimeout(() => controller.abort(), 2000); // 2s timeout

                const response = await fetch(`${this.apiBase}/state`, { signal: controller.signal });
                clearTimeout(timeoutId);

                if (!response.ok) throw new Error("API Error");
                this.data = await response.json();
                console.log("LIVE API connection successful.");
            } catch (e) {
                console.warn("LIVE API connection failed (" + e.message + "). Switching to local data.");
                return this.fetchLocalData();
            }
        } else {
            return this.fetchLocalData();
        }
    }

    async fetchLocalData() {
        // 1. Check global variable (fastest, injected by script)
        if (window.MOCK_DATA) {
            this.data = window.MOCK_DATA;
            // Add a flag to indicate this is synthetic/scanned data
            this.data._source = "static_script";
            return this.data;
        }

        // 2. Fetch JSON file
        try {
            const response = await fetch(this.staticBase);
            if(response.ok) {
                this.data = await response.json();
                this.data._source = "json_file";
            } else {
                throw new Error("Static JSON fetch failed");
            }
        } catch (e) {
            console.warn("Failed to fetch static JSON:", e);
            this.data = this.getEmptyState();
        }
        return this.data;
    }

    getEmptyState() {
        return {
            system_stats: { cpu_usage: 0, memory_usage: 0, active_tasks: 0, version: "Offline" },
            files: [],
            agents: [],
            reports: [],
            prompts: []
        };
    }

    // Robust Accessors

    get(path, defaultValue = "N/A") {
        return path.split('.').reduce((o, p) => (o ? o[p] : defaultValue), this.data) || defaultValue;
    }

    getSystemStats() {
        // If "Live Mode" is on but we are using static data, maybe simulate some fluctuations
        const stats = this.data?.system_stats || {};
        if (this.useApi && this.data?._source) {
             // We are in simulated live mode (using static data but pretending)
             return {
                 ...stats,
                 cpu_usage: Math.min(100, Math.max(0, (stats.cpu_usage || 10) + (Math.random() * 10 - 5))).toFixed(1),
                 memory_usage: Math.min(100, Math.max(0, (stats.memory_usage || 30) + (Math.random() * 5 - 2.5))).toFixed(1),
                 active_tasks: Math.max(0, (stats.active_tasks || 2) + Math.floor(Math.random() * 3 - 1))
             };
        }
        return stats;
    }

    getFiles() {
        return this.data?.files || [];
    }

    getAgents() {
        return this.data?.agents || [];
    }

    getReports() {
        return this.data?.reports || [];
    }

    getPrompts() {
        return this.data?.prompts || [];
    }

    async getFileContent(path) {
        if (this.useApi && !this.data?._source) {
            // Real API call
            try {
                const res = await fetch(`/${path}`);
                if (!res.ok) throw new Error("File not found");
                return await res.text();
            } catch(e) {
                return `Error loading file via API: ${e.message}`;
            }
        } else {
            // Attempt to fetch relatively if running statically
            try {
                // If path is absolute from repo root like 'README.md', and we are in 'showcase/', we need '../README.md'
                const relPath = `../${path}`;
                const res = await fetch(relPath);
                if (res.ok) {
                    return await res.text();
                }
            } catch (e) {
                console.warn("Failed to fetch static file:", path, e);
            }
            return "File content viewing is only available when running a local server (e.g. 'python -m http.server').\n\nRun 'python services/ui_backend.py' to enable full API features.";
        }
    }
}

// Global instance
window.dataManager = new DataManager();
