window.SYSTEM_BRAIN_DATA = {
  "metrics": {
    "active_agents_count": 278,
    "active_agents_list": [
      "writer.yaml",
      "quant.yaml",
      "archivist.yaml",
      "risk_officer.yaml",
      "index.html",
      "__init__.py",
      "risk_analyst.py",
      "ratio_calculator.py",
      "index.html",
      "analyst.py",
      "supervisor.py",
      "legal.py",
      "market.py",
      "fundamental_analyst_agent.py",
      "market_sentiment_agent.py",
      "query_understanding_agent.py",
      "RAG_AGENT_README.md",
      "index.html",
      "newsletter_layout_specialist_agent.py",
      "quantum_monte_carlo_agent.py",
      "lingua_maestro.py",
      "archive_manager_agent.py",
      "code_alchemist.py",
      "event_driven_risk_agent.py",
      "README.md",
      "geopolitical_risk_agent.py",
      "rag_agent.py",
      "model.html",
      "report_generator_agent.py",
      "sense_weaver.py",
      "algo_trading_agent.py",
      "reflector_agent.py",
      "AGENTS.md",
      "__init__.py",
      "regulatory_compliance_agent.py",
      "crypto_agent.py",
      "meta_cognitive_agent.py",
      "knowledge_contribution_agent.py",
      "profile_agent.py",
      "data_verification_agent.py",
      "portfolio_optimization_agent.py",
      "agent_base.py",
      "strategic_foresight_agent.py",
      "adaptive_algo_agent.py",
      "meta_19_agent.py",
      "lexica_agent.py",
      "directory_manifest.jsonld",
      "hnasp_agent.py",
      "prompt_tuner.py",
      "supply_chain_risk_agent.py",
      "risk_assessment_agent.py",
      "red_team_agent.py",
      "critique_swarm.py",
      "industry_specialist_agent.py",
      "behavioral_economics_agent.py",
      "market_making_agent.py",
      "alternative_data_agent.py",
      "AGENT_DEVELOPMENT.md",
      "fraud_detection_agent.py",
      "discussion_chair_agent.py",
      "news_bot.py",
      "financial_modeling_agent.py",
      "catalyst_agent.py",
      "data_visualization_agent.py",
      "AGENT_CATALOG.md",
      "machine_learning_model_training_agent.py",
      "result_aggregation_agent.py",
      "echo_agent.py",
      "adaptive_agent.py",
      "snc_analyst_agent.py",
      "technical_analyst_agent.py",
      "legal_agent.py",
      "prompt_generation_agent.py",
      "quantitative_risk_agent.py",
      "black_swan_agent.py",
      "macroeconomic_analysis_agent.py",
      "natural_language_generation_agent.py",
      "agent_forge.py",
      "data_retrieval_agent.py",
      "anomaly_detection_agent.py",
      "prediction_market_agent.py",
      "cyclical_reasoning_agent.py",
      "evolutionary_optimizer.py",
      "index.html",
      "impact_analysis_agent.py",
      "index.html",
      "xai_skill.py",
      "counterfactual_reasoning_skill.py",
      "hybrid_forecasting_skill.py",
      "skprompt.txt",
      "index.html",
      "__init__.py",
      "index.html",
      "skprompt.txt",
      "index.html",
      "config.json",
      "skprompt.txt",
      "index.html",
      "__init__.py",
      "index.html",
      "skprompt.txt",
      "index.html",
      "config.json",
      "skprompt.txt",
      "index.html",
      "config.json",
      "skprompt.txt",
      "index.html",
      "config.json",
      "skprompt.txt",
      "index.html",
      "__init__.py",
      "skprompt.txt",
      "index.html",
      "__init__.py",
      "index.html",
      "skprompt.txt",
      "index.html",
      "config.json",
      "index.html",
      "directory_manifest.jsonld",
      "agent.py",
      "index.html",
      "directory_manifest.jsonld",
      "system_prompt.txt",
      "index.html",
      "management_assessment_agent.py",
      "optimized_gallery_agent.py",
      "regulatory_snc_agent.py",
      "credit_sentry_agent.py",
      "market_regime_agent.py",
      "deep_sector_analyst.py",
      "sovereign_ai_analyst_agent.py",
      "financial_covenant_agent.py",
      "__init__.py",
      "crypto_arbitrage_agent.py",
      "strategic_snc_agent.py",
      "credit_conformance_agent.py",
      "credit_snc.py",
      "quantum_search_agent.py",
      "root_node_agent.py",
      "macro_liquidity_agent.py",
      "institutional_radar_agent.py",
      "counterparty_risk_agent.py",
      "directory_manifest.jsonld",
      "quantum_strategy_agent.py",
      "credit_lawyer.py",
      "credit_risk_controller_agent.py",
      "forensic_accountant_agent.py",
      "retail_alpha_agent.py",
      "blindspot_agent.py",
      "narrative_intelligence_agent.py",
      "peer_comparison_agent.py",
      "quantum_risk_agent.py",
      "risk_copilot_agent.py",
      "sentinel_agent.py",
      "technical_covenant_agent.py",
      "quantum_retrieval_agent.py",
      "monte_carlo_risk_agent.py",
      "portfolio_manager_agent.py",
      "distressed_surveillance_agent.py",
      "institutional_trend_agent.py",
      "quantum_scenario_agent.py",
      "index.html",
      "state_anchor.py",
      "__init__.py",
      "tool_manager.py",
      "adaptive_conviction.py",
      "index.html",
      "v23_template_agent.py",
      "v23_adaptive_rpc_agent.py",
      "v26_template_agent.py",
      "index.html",
      "on_demand_software_gen.md",
      "planner_agent.py",
      "spec_architect_agent.py",
      "__init__.py",
      "test_agent.py",
      "reviewer_agent.py",
      "directory_manifest.jsonld",
      "integration_agent.py",
      "coder_agent.py",
      "documentation_agent.py",
      "credit_agent_base.py",
      "__init__.py",
      "archivist.py",
      "writer.py",
      "quant.py",
      "orchestrator.py",
      "financial_news_sub_agent.py",
      "index.html",
      "internal_systems_agent.py",
      "financial_document_agent.py",
      "AGENTS.md",
      "compliance_kyc_agent.py",
      "directory_manifest.jsonld",
      "data_ingestion_agent.py",
      "market_alternative_data_agent.py",
      "git_repo_sub_agent.py",
      "index.html",
      "index.html",
      "README.md",
      "run_guardian.py",
      "schemas.py",
      "prompts.py",
      "tools.py",
      "agent.py",
      "index.html",
      "test_agent.py",
      "test_tools.py",
      "index.html",
      "capacity_planner_agent.py",
      "index.html",
      "__init__.py",
      "risk_model_server.py",
      "financial_data_server.py",
      "index.html",
      "memory_mixin.py",
      "__init__.py",
      "redundancy_optimization_mixin.py",
      "audit_mixin.py",
      "news_desk_orchestrator.py",
      "credit_risk_orchestrator.py",
      "index.html",
      "creditsentry_orchestrator.py",
      "AGENTS.md",
      "directory_manifest.jsonld",
      "hybrid_orchestrator.py",
      "workflow.py",
      "meta_orchestrator.py",
      "workflow_manager.py",
      "task.py",
      "odyssey_hub_agent.py",
      "parallel_orchestrator.py",
      "telecommunication_services.py",
      "index.html",
      "healthcare.py",
      "industrials.py",
      "energy.py",
      "directory_manifest.jsonld",
      "utilities.py",
      "real_estate.py",
      "consumer_discretionary.py",
      "materials.py",
      "consumer_staples.py",
      "financials.py",
      "technology.py",
      "persona_communication_agent.py",
      "index.html",
      "auto_architect_agent.py",
      "crisis_simulation_agent.py",
      "AGENTS.md",
      "__init__.py",
      "chronos_agent.py",
      "credit_risk_assessment_agent.py",
      "didactic_architect_agent.py",
      "odyssey_meta_agent.py",
      "skill_harvester_agent.py",
      "counterparty_risk_agent.py",
      "directory_manifest.jsonld",
      "evolutionary_architect_agent.py",
      "didactic_architect.py",
      "sentiment_analysis_meta_agent.py",
      "portfolio_monitoring_ews_agent.py",
      "evolutionary_architect.py",
      "narrative_summarization_agent.py",
      "base_agent.py",
      "index.html",
      "code_weaver.py",
      "risk_guardian.py",
      "__init__.py",
      "reviewer_agent.py",
      "swarm_runner.py",
      "quantitative_analyst.py",
      "monitoring_agent.py",
      "news_bot.py",
      "market_scanner.py",
      "fundamental_analyst.py"
    ],
    "knowledge_nodes_count": 792,
    "knowledge_coverage": 12.2,
    "total_nodes": 6493,
    "total_edges": 6560,
    "cognitive_load": 10.1
  },
  "synapses": [
    {
      "name": "logging_utils.py",
      "type": "core",
      "connections": 465
    },
    {
      "name": "chronos.py",
      "type": "code",
      "connections": 426
    },
    {
      "name": "JPM HOUSE VIEW",
      "type": "strategy",
      "connections": 322
    },
    {
      "name": "fix_json_v2.py",
      "type": "code",
      "connections": 313
    },
    {
      "name": "verify_system_brain.py",
      "type": "code",
      "connections": 222
    },
    {
      "name": "JPM AI INFRASTRUCTURE",
      "type": "core",
      "connections": 176
    },
    {
      "name": "test_sentiment_graph.py",
      "type": "code",
      "connections": 152
    },
    {
      "name": "completers.py",
      "type": "code",
      "connections": 124
    },
    {
      "name": "agent_base.py",
      "type": "agent",
      "connections": 119
    },
    {
      "name": "reproduce_debug_mode.py",
      "type": "code",
      "connections": 73
    }
  ],
  "hardware": {
    "cpu_usage": 25.0,
    "memory_usage_pct": 5.1,
    "memory_available_gb": 7.37,
    "gpu_usage": 39.7,
    "tpu_usage": 19.1,
    "gpu_memory_used_gb": 6.35,
    "tpu_memory_used_gb": 6.12
  },
  "system_status": "OPERATIONAL",
  "timestamp": 1771208448.242687
};