backend:
  - any: ['core/**', 'tests/**', 'requirements.txt', '*.py']
frontend:
  - any: ['services/webapp/**', 'showcase/**', '*.js', '*.html', '*.css']
rust:
  - any: ['core/experimental/adamos_kernel/**']
docs:
  - any: ['docs/**', '*.md', 'mkdocs.yml']
ci:
  - any: ['.github/**']
