import os
import sys
from playwright.sync_api import sync_playwright

def verify_archive_ui():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        # 1. Open Archive
        archive_path = os.path.abspath("showcase/market_mayhem_archive.html")
        print(f"Opening {archive_path}...")
        try:
            page.goto(f"file://{archive_path}")
            page.wait_for_load_state("domcontentloaded")
        except Exception as e:
            print(f"Error loading page: {e}")
            return

        # 2. Verify System Dashboard
        print("Verifying System Dashboard...")
        dashboard = page.query_selector('.system-dashboard')
        if not dashboard:
            print("❌ System Dashboard NOT found!")
        else:
            print("✅ System Dashboard found.")
            # Check for specific metrics inside
            metrics = dashboard.query_selector_all('.metric .label')
            labels = [m.inner_text() for m in metrics]
            print(f"   Dashboard Metrics found: {labels}")
            if "MARKET REGIME" in labels and "SYSTEM HEALTH" in labels:
                 print("✅ Expected Dashboard Metrics found.")
            else:
                 print("❌ specific Dashboard Metrics missing.")

        # 3. Verify Chart Datasets (indirectly via existence of canvas, detailed verification is hard without JS execution context)
        # We can check if the canvas exists, and maybe inspect `chartData` variable if it's global
        print("Verifying Chart Configuration...")
        canvas = page.query_selector('#sentimentChart')
        if not canvas:
             print("❌ Chart canvas NOT found!")
        else:
             print("✅ Chart canvas found.")
             # Check if we can access the chart data
             try:
                 chart_datasets = page.evaluate("() => typeof chartData !== 'undefined' ? chartData.datasets.length : 0")
                 print(f"   Chart Datasets count: {chart_datasets}")
                 if chart_datasets >= 2: # Sentiment + Moving Average + Conviction?
                     print("✅ Multiple datasets detected (likely Sentiment + MA + Conviction).")
                 else:
                     print("⚠️ Only 1 dataset detected (probably just Sentiment).")
             except Exception as e:
                 print(f"   Could not evaluate chart data: {e}")

        # 4. Verify List Item Metrics
        print("Verifying List Item Metrics...")
        list_items = page.query_selector_all('.archive-item')
        if list_items:
            first_item = list_items[0]
            text = first_item.inner_text()
            if "CONV:" in text and "SEM:" in text:
                print(f"✅ Metrics (CONV, SEM) found in list item: '{text[:50]}...'")
            else:
                print(f"❌ Metrics (CONV, SEM) NOT found in list item: '{text[:50]}...'")
        else:
            print("❌ No archive items found.")

        # 5. Open a Report
        print("Navigating to a report...")
        # Find a link to a report (prefer one generated by the script, e.g. .html)
        # We look for a link that is NOT daily_briefings_library etc.
        # Specifically target a known generated file
        target_link = page.query_selector('a[href="newsletter_market_mayhem_jan_2026.html"]')

        if target_link:
            print(f"Clicking link to {target_link.get_attribute('href')}...")
            target_link.click()
            page.wait_for_load_state('networkidle')

            # 6. Verify HUD Sidebar
            print("Verifying HUD Sidebar...")
            sidebar = page.query_selector('.cyber-sidebar')
            if sidebar:
                sidebar_text = sidebar.inner_text().upper()
                # Check for "Agent Conviction", "Reviewer Agent Log"
                # Note: CSS text-transform: uppercase makes these uppercase in inner_text()
                if "AGENT CONVICTION" in sidebar_text:
                    print("✅ HUD Sidebar: 'Agent Conviction' found.")
                else:
                    print(f"❌ HUD Sidebar: 'Agent Conviction' NOT found. Sidebar text sample: {sidebar_text[:100]}...")

                if "REVIEWER AGENT LOG" in sidebar_text:
                    print("✅ HUD Sidebar: 'Reviewer Agent Log' found.")
                else:
                    print("❌ HUD Sidebar: 'Reviewer Agent Log' NOT found.")

                # Check for Semantic/Probability if they are rendered as titles or labels
                if "SEMANTIC ANALYSIS" in sidebar_text or "SEMANTIC" in sidebar_text:
                     print("✅ HUD Sidebar: Semantic score section found.")

            else:
                print("❌ HUD Sidebar NOT found.")
        else:
            print("❌ No report links found.")

        browser.close()

if __name__ == "__main__":
    verify_archive_ui()
