from __future__ import annotations
from enum import Enum
from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field, ConfigDict

class MetricUnit(str, Enum):
    USD = "USD"
    EUR = "EUR"
    PERCENT = "PERCENT"
    RATIO = "RATIO"
    COUNT = "COUNT"

class FinancialMetric(BaseModel):
    """
    Represents a strictly validated financial metric.
    """
    model_config = ConfigDict(populate_by_name=True)

    metric_name: str = Field(..., description="The standardized name of the metric (e.g., 'EBITDA')")
    value: float = Field(..., description="The numerical value of the metric")
    unit: MetricUnit = Field(..., description="The unit of measurement")
    period: str = Field(..., description="The time period (e.g., 'FY2023', 'Q3-2024')")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Conviction score (0.0 to 1.0)")
    source: str = Field(..., description="Origin of the data (e.g., 'SEC Filing', 'Yahoo Finance')")
    provenance_id: Optional[str] = Field(None, description="Hash/ID of the source document")

class IntentCategory(str, Enum):
    DEEP_DIVE = "DEEP_DIVE"
    RISK_ALERT = "RISK_ALERT"
    MARKET_UPDATE = "MARKET_UPDATE"
    UNCERTAIN = "UNCERTAIN"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"

class RoutingResult(BaseModel):
    """
    Result of the Semantic Router classification.
    """
    intent: IntentCategory
    confidence_score: float
    routing_metadata: Dict[str, Any] = Field(default_factory=dict)

class GraphNode(BaseModel):
    """
    Represents a node in the Knowledge Graph for planning.
    """
    id: str
    label: str
    properties: Dict[str, Any]

class PlanStep(BaseModel):
    """
    A single step in a Neuro-Symbolic Plan.
    """
    step_id: str
    action: str = Field(..., description="The action to perform (e.g., 'FETCH_DATA', 'RUN_SIMULATION')")
    target_entity: str
    parameters: Dict[str, Any]
    rationale: str

class ExecutionPlan(BaseModel):
    """
    A complete execution plan generated by the Planner.
    """
    plan_id: str
    steps: List[PlanStep]
    estimated_complexity: str

class CritiqueResult(BaseModel):
    """
    Output from the Self-Reflection Agent.
    """
    passed: bool
    feedback: str
    missing_data: List[str] = Field(default_factory=list)
    score: float = Field(..., ge=0.0, le=1.0)

class IngestedArtifact(BaseModel):
    """
    Represents a document or data point processed by the Ingestion Engine.
    """
    content: str
    artifact_type: str
    source_url: Optional[str] = None
    conviction_score: float
    entities: List[str] = Field(default_factory=list)
    timestamp: str

class DeepDiveRequest(BaseModel):
    """
    Standardized request structure for a Deep Dive analysis.
    """
    query: str
    user_id: str
    thread_id: str
    context: Dict[str, Any] = Field(default_factory=dict)

# --- Legacy / Core Graph Models to satisfy imports ---

class V23KnowledgeGraph(BaseModel):
    """
    The core Knowledge Graph container for v23.5.
    """
    nodes: Dict[str, Dict[str, Any]] = Field(default_factory=dict)
    edges: List[Dict[str, Any]] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    version: str = "23.5"

class HyperDimensionalKnowledgeGraph(BaseModel):
    """
    Top-level container for the HDKG output.
    """
    v23_knowledge_graph: V23KnowledgeGraph

    # Allow extra fields for forward compatibility
    model_config = ConfigDict(extra='allow')
