from __future__ import annotations
from enum import Enum
from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field, ConfigDict

# ==============================================================================
# SECTION 1: ENUMS & CORE PRIMITIVES
# ==============================================================================

class MetricUnit(str, Enum):
    USD = "USD"
    EUR = "EUR"
    PERCENT = "PERCENT"
    RATIO = "RATIO"
    COUNT = "COUNT"
    BPS = "BPS"  # Added useful financial unit

class IntentCategory(str, Enum):
    DEEP_DIVE = "DEEP_DIVE"
    RISK_ALERT = "RISK_ALERT"
    MARKET_UPDATE = "MARKET_UPDATE"
    UNCERTAIN = "UNCERTAIN"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"

class Meta(BaseModel):
    target: str
    generated_at: str
    model_version: Literal["Adam-v23.5-Apex-Architect"]

# ==============================================================================
# SECTION 2: AGENTIC INFRASTRUCTURE & WORKFLOW
# (Routing, Planning, Ingestion, validation)
# ==============================================================================

class FinancialMetric(BaseModel):
    """
    Represents a strictly validated financial metric, traceable to a source.
    """
    model_config = ConfigDict(populate_by_name=True)

    metric_name: str = Field(..., description="The standardized name (e.g., 'EBITDA')")
    value: float = Field(..., description="The numerical value")
    unit: MetricUnit = Field(..., description="The unit of measurement")
    period: str = Field(..., description="The time period (e.g., 'FY2023')")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Conviction score")
    source: str = Field(..., description="Origin (e.g., 'SEC Filing', 'Bloomberg')")
    provenance_id: Optional[str] = Field(None, description="Hash/ID of source document")

class RoutingResult(BaseModel):
    """Result of the Semantic Router classification."""
    intent: IntentCategory
    confidence_score: float
    routing_metadata: Dict[str, Any] = Field(default_factory=dict)

class PlanStep(BaseModel):
    """A single step in a Neuro-Symbolic Plan."""
    step_id: str
    action: str = Field(..., description="Action to perform (e.g., 'FETCH_DATA')")
    target_entity: str
    parameters: Dict[str, Any]
    rationale: str

class ExecutionPlan(BaseModel):
    """A complete execution plan generated by the Planner."""
    plan_id: str
    steps: List[PlanStep]
    estimated_complexity: str

class CritiqueResult(BaseModel):
    """Output from the Self-Reflection/Critique Agent."""
    passed: bool
    feedback: str
    missing_data: List[str] = Field(default_factory=list)
    score: float = Field(..., ge=0.0, le=1.0)

class IngestedArtifact(BaseModel):
    """Represents raw data processed by the Ingestion Engine."""
    content: str
    artifact_type: str
    source_url: Optional[str] = None
    conviction_score: float
    entities: List[str] = Field(default_factory=list)
    timestamp: str

class DeepDiveRequest(BaseModel):
    """Standardized request structure for a Deep Dive analysis."""
    query: str
    user_id: str
    thread_id: str
    context: Dict[str, Any] = Field(default_factory=dict)

# ==============================================================================
# SECTION 3: DOMAIN MODELS - PHASE 1: ENTITY & MANAGEMENT
# ==============================================================================

class LegalEntity(BaseModel):
    name: str
    lei: str
    jurisdiction: str
    sector: str

class ManagementAssessment(BaseModel):
    capital_allocation_score: float = Field(description="Score 0-10 on capital allocation efficiency")
    alignment_analysis: str = Field(description="Analysis of insider buying/selling")
    key_person_risk: Literal["High", "Med", "Low"]

class CompetitivePositioning(BaseModel):
    moat_status: Literal["Wide", "Narrow", "None"]
    technology_risk_vector: str

class EntityEcosystem(BaseModel):
    legal_entity: LegalEntity
    management_assessment: ManagementAssessment
    competitive_positioning: CompetitivePositioning

# ==============================================================================
# SECTION 4: DOMAIN MODELS - PHASE 2: DEEP FUNDAMENTAL & VALUATION
# ==============================================================================

class Fundamentals(BaseModel):
    revenue_cagr_3yr: str
    ebitda_margin_trend: Literal["Expanding", "Contracting", "Stable"]

class DCFModel(BaseModel):
    wacc_assumption: str
    terminal_growth: str
    intrinsic_value_estimate: float

class MultiplesAnalysis(BaseModel):
    current_ev_ebitda: float
    peer_median_ev_ebitda: float
    verdict: Literal["Undervalued", "Overvalued", "Fair"]

class PriceTargets(BaseModel):
    bear_case: float
    base_case: float
    bull_case: float

class ValuationEngine(BaseModel):
    dcf_model: DCFModel
    multiples_analysis: MultiplesAnalysis
    price_targets: PriceTargets

class EquityAnalysis(BaseModel):
    fundamentals: Fundamentals
    valuation_engine: ValuationEngine

# ==============================================================================
# SECTION 5: DOMAIN MODELS - PHASE 3: CREDIT, COVENANTS & SNC
# ==============================================================================

class PrimaryFacilityAssessment(BaseModel):
    facility_type: str
    collateral_coverage: Literal["Strong", "Adequate", "Weak"]
    repayment_capacity: str

class DialogueTurn(BaseModel):
    speaker: Literal["Regulator", "Strategist"]
    argument: str
    counter_point: Optional[str] = None

class RiskDialogue(BaseModel):
    turns: List[DialogueTurn]
    conclusion: str
    override_applied: bool = False

class SNCRatingModel(BaseModel):
    overall_borrower_rating: Literal["Pass", "Special Mention", "Substandard", "Doubtful", "Loss"]
    rationale: str
    primary_facility_assessment: PrimaryFacilityAssessment
    legacy_rating: Optional[str] = Field(None, description="Legacy Leverage/Coverage model rating")
    model_consensus: Optional[bool] = Field(None, description="True if Legacy and New models agree")
    conviction_score: Optional[float] = Field(None, description="Internal confidence score (0.0-1.0)")
    risk_dialogue: Optional[RiskDialogue] = Field(None, description="Debate between Regulatory and Strategic agents")

class CovenantRiskAnalysis(BaseModel):
    primary_constraint: str = Field(description="The primary restrictive covenant or 'Choke Point'")
    current_level: float
    breach_threshold: float
    headroom_assessment: str = Field(description="Analysis of headroom (e.g., '15% Cushion')")

class CreditAnalysis(BaseModel):
    snc_rating_model: SNCRatingModel
    cds_market_implied_rating: str
    covenant_risk_analysis: CovenantRiskAnalysis

# ==============================================================================
# SECTION 6: DOMAIN MODELS - PHASE 4: RISK, SIMULATION & QUANTUM
# ==============================================================================

class QuantumScenario(BaseModel):
    scenario_name: str
    probability: Literal["Low", "Med", "High"]
    impact_severity: Literal["Critical", "High", "Moderate"]
    estimated_impact_ev: str

class TradingDynamics(BaseModel):
    short_interest: str
    liquidity_risk: Literal["Low", "Med", "High"]

class SimulationEngine(BaseModel):
    monte_carlo_default_prob: str
    quantum_scenarios: List[QuantumScenario]
    trading_dynamics: TradingDynamics
    simulation_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Detailed simulation data for visualization")

# ==============================================================================
# SECTION 7: DOMAIN MODELS - PHASE 5: SYNTHESIS
# ==============================================================================

class FinalVerdict(BaseModel):
    recommendation: Literal["Strong Buy", "Buy", "Hold", "Sell", "Strong Sell"]
    conviction_level: int = Field(ge=1, le=10)
    time_horizon: str
    rationale_summary: str
    justification_trace: List[str]

class StrategicSynthesis(BaseModel):
    m_and_a_posture: Literal["Buyer", "Seller", "Neutral"]
    final_verdict: FinalVerdict

# ==============================================================================
# SECTION 8: THE UNIFIED KNOWLEDGE GRAPH
# ==============================================================================

class Nodes(BaseModel):
    """
    The rigid, schema-enforced core of the financial analysis.
    """
    entity_ecosystem: EntityEcosystem
    equity_analysis: EquityAnalysis
    credit_analysis: CreditAnalysis
    simulation_engine: SimulationEngine
    strategic_synthesis: StrategicSynthesis

class GraphEdge(BaseModel):
    """
    Represents semantic relationships between components,
    allowing the rigid Nodes to be connected dynamically.
    """
    source_id: str
    target_id: str
    relation_type: str
    properties: Dict[str, Any] = Field(default_factory=dict)

class V23KnowledgeGraph(BaseModel):
    """
    The merged Core Knowledge Graph.
    It combines the strict 'Nodes' structure from Source 2 with the 
    flexible 'Edges' and metadata capabilities from Source 1.
    """
    model_config = ConfigDict(populate_by_name=True)

    meta: Meta
    
    # The structured domain analysis
    nodes: Nodes
    
    # Flexible connections (from Source 1 capability)
    edges: List[GraphEdge] = Field(default_factory=list)
    
    # Traceability back to the Agentic Infrastructure (Source 1 integration)
    execution_trace: Optional[ExecutionPlan] = None
    ingested_artifacts_ref: Optional[List[str]] = Field(default_factory=list, description="IDs of artifacts used")
    
    # Extensible metadata
    extended_metadata: Dict[str, Any] = Field(default_factory=dict)

class HyperDimensionalKnowledgeGraph(BaseModel):
    """
    Top-level container for the HDKG output.
    """
    model_config = ConfigDict(populate_by_name=True, extra='allow')
    
    v23_knowledge_graph: V23KnowledgeGraph
