import unittest
from core.simulation.sovereign import Sovereign, Resource, Military
from core.simulation.economy import EconomyEngine
from core.simulation.demographics import DemographicsEngine, PopulationSegment

class TestSimulation(unittest.TestCase):
    def setUp(self):
        self.sov = Sovereign(
            id="test-1",
            name="TestNation",
            region="TestRegion",
            ideology="Market Democracy",
            resources=[Resource(name="Oil", amount=1.5, market_price=10.0)],
            demographics=[PopulationSegment(label="General", percentage=1.0)]
        )

    def test_economy_initialization(self):
        self.assertIsNotNone(self.sov.economy)
        self.assertEqual(self.sov.economy.gdp_growth, 0.02)

    def test_military_initialization(self):
        self.assertIsNotNone(self.sov.military)
        # Default readiness is 0.5
        self.assertEqual(self.sov.military.readiness, 0.5)

    def test_market_simulation(self):
        # Create two sovereigns
        sov2 = Sovereign(
            id="test-2",
            name="TestNation2",
            region="TestRegion",
            ideology="Digital Autocracy",
            resources=[Resource(name="Oil", amount=0.1, market_price=10.0)], # Scarcity
            demographics=[]
        )

        # Run market sim
        EconomyEngine.simulate_global_market([self.sov, sov2])

        # Price should go up because demand (implied by industries) > supply (1.6 total)
        # Industries for Market Dem & Autocracy both likely use Oil (Energy)
        # Wait, simulate_global_market logic:
        # Supply = 1.6
        # Demand: generated by industries.
        # Market Democracy -> Energy ind -> Oil dependence 0.9. Output 1.8. Demand ~1.62
        # Autocracy -> Energy ind -> Oil dependence 0.9. Output 1.8. Demand ~1.62
        # Total Demand > 3.0. Supply 1.6. Scarcity > 1. Price should rise.

        self.assertGreater(self.sov.resources[0].market_price, 10.0)

    def test_demographic_shift(self):
        initial_sentiment = self.sov.demographics[0].sentiment
        DemographicsEngine.simulate_shift(self.sov, 1)
        # Sentiment drifts randomly, difficult to assert exact value, but should be within bounds
        self.assertTrue(0.0 <= self.sov.demographics[0].sentiment <= 1.0)

if __name__ == '__main__':
    unittest.main()
