from __future__ import annotations
import unittest
import asyncio
from core.agents.meta_agents.crisis_simulation_agent import CrisisSimulationMetaAgent
from core.schemas.crisis_simulation import CrisisSimulationInput, RiskEntity


class TestCrisisSimulationMetaAgent(unittest.TestCase):

    def test_crisis_simulation_execution(self):
        """
        Tests the full execution of the CrisisSimulationMetaAgent with mock data.
        """
        # 1. Arrange
        agent_config = {"name": "CrisisSimulationTestAgent"}
        agent = CrisisSimulationMetaAgent(config=agent_config)

        # Create a mock risk portfolio
        mock_portfolio = [
            RiskEntity(
                risk_id="R-CYB-01",
                description="ERP Security Compromise.",
                velocity="Instant",
                persistence="Persistent",
                interconnectivity=["R-FIN-01", "R-OPS-03"],
                strategic_objective="Q4 Revenue Growth",
                quantitative_exposure=5000000.0,
                control_effectiveness=0.4,
                control_strength="Weak"
            ),
            RiskEntity(
                risk_id="R-OPS-03",
                description="Supply Chain Halt.",
                velocity="Instant",
                persistence="Transient",
                interconnectivity=[],
                strategic_objective="Operational Efficiency",
                quantitative_exposure=500000.0,
                control_effectiveness=0.8,
                control_strength="Strong"
            ),
            RiskEntity(
                risk_id="R-FIN-01",
                description="Quarterly Revenue Miss.",
                velocity="Gradual",
                persistence="Persistent",
                interconnectivity=[],
                strategic_objective="Q4 Revenue Growth",
                quantitative_exposure=200000.0,
                control_effectiveness=0.6,
                control_strength="Moderate"
            )
        ]

        simulation_input = CrisisSimulationInput(
            risk_portfolio=mock_portfolio,
            current_date="2024-11-25",
            user_scenario="A sophisticated ransomware gang encrypts the main ERP database on the last day of the fiscal quarter. Backups are found to be corrupted."
        )

        # 2. Act
        # The agent's execute method is async, so we run it in an event loop.
        result = asyncio.run(agent.execute(simulation_input))

        # 3. Assert
        self.assertIsNotNone(result)
        # With the active v23 Graph, the summary should contain the generated report title
        self.assertIn("Crisis Simulation Report", result.executive_summary)
        # It should calculate some loss
        self.assertIn("Estimated Loss", result.executive_summary)

        # The log length depends on the graph execution, just check it has entries
        self.assertTrue(len(result.crisis_simulation_log) > 0)

        # Verify the log contains system events generated by the graph
        risk_ids = [entry.risk_id_cited for entry in result.crisis_simulation_log]
        # The graph generates "SYS-INIT" and "SYS-CONTAGION" (or similar from SectorImpactEngine)
        self.assertTrue(any("SYS" in rid for rid in risk_ids))

        # Recommendations are static in the graph wrapper currently (or checking default string)
        self.assertIn("detailed graph trace", result.recommendations)


if __name__ == '__main__':
    unittest.main()
