import React, { useState, useEffect } from 'react';
import GlassCard from '../common/GlassCard';
import { dataManager } from '../../utils/DataManager';
import ReactMarkdown from 'react-markdown';
import { FileText, AlertCircle } from 'lucide-react';

const IntelFeed = () => {
    const [news, setNews] = useState([]);
    const [selectedItem, setSelectedItem] = useState(null);

    useEffect(() => {
        const fetchNews = async () => {
            const data = await dataManager.getData('/news/feed');
            if (data) {
                setNews(data);
                // Select first item by default if available
                if (data.length > 0) setSelectedItem(data[0]);
            }
        };
        fetchNews();
    }, []);

    // Mock full report content for the demo
    const getMockContent = (item) => {
        if (!item) return '';
        return `
## ${item.title}

**Date:** ${new Date(item.timestamp).toLocaleDateString()}
**Type:** ${item.type.toUpperCase()}
**Priority:** ${item.priority.toUpperCase()}

---

### Executive Summary

This is a simulated ${item.type} report generated by the ADAM system. In a production environment, this would contain the full analysis text generated by the *FundamentalAnalystAgent* or *MarketSentimentAgent*.

### Key Findings

- **Trend Analysis:** Positive momentum observed in the sector.
- **Risk Assessment:** Moderate volatility expected in the short term.
- **Strategic Recommendation:** Accumulate on dips.

### Detailed Analysis

The market has shown resilience despite macroeconomic headwinds. Our algorithms detect a significant shift in sentiment regarding ${item.title.split(' ')[0]}.

> "Volatility is the price of admission for high performance."

### Data Points

| Metric | Value | Change |
| :--- | :--- | :--- |
| Alpha | 1.25 | +0.05 |
| Beta | 0.85 | -0.02 |
| Sentiment | 0.72 | +0.10 |

*End of Report*
        `;
    };

    return (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-140px)]">
            {/* Feed List */}
            <div
                className="lg:col-span-1 space-y-4 overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-500/30 rounded"
                tabIndex={0}
                role="region"
                aria-label="Intel Feed Items"
            >
                <h2 className="text-xl font-mono text-cyan-400 font-bold mb-4">Intel Feed</h2>
                {news.map((item) => (
                    <button
                        key={item.id}
                        onClick={() => setSelectedItem(item)}
                        aria-current={selectedItem?.id === item.id ? 'true' : undefined}
                        className={`w-full text-left p-4 rounded-lg border transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-cyan-500 ${
                            selectedItem?.id === item.id
                            ? 'bg-slate-800 border-cyan-500/50 shadow-lg shadow-cyan-900/20'
                            : 'bg-slate-900/50 border-slate-700 hover:bg-slate-800 hover:border-slate-600'
                        }`}
                    >
                        <div className="flex justify-between items-start mb-2">
                            <span className={`text-xs px-2 py-0.5 rounded uppercase font-bold tracking-wider ${
                                item.type === 'flash' ? 'bg-amber-900/50 text-amber-500' : 'bg-blue-900/50 text-blue-400'
                            }`}>
                                {item.type}
                            </span>
                            <span className="text-xs text-slate-500">{new Date(item.timestamp).toLocaleTimeString()}</span>
                        </div>
                        <h3 className="text-slate-200 font-medium leading-snug mb-2">{item.title}</h3>
                        {item.priority === 'high' && (
                            <div className="flex items-center text-rose-500 text-xs">
                                <AlertCircle size={12} className="mr-1" />
                                High Priority
                            </div>
                        )}
                    </button>
                ))}
            </div>

            {/* Reading Pane */}
            <GlassCard className="lg:col-span-2 flex flex-col h-full overflow-hidden">
                {selectedItem ? (
                    <div className="h-full flex flex-col">
                        <div className="flex items-center space-x-3 mb-6 pb-4 border-b border-slate-700/50">
                            <div className="p-3 bg-slate-800 rounded-lg text-cyan-400">
                                <FileText size={24} />
                            </div>
                            <div>
                                <h1 className="text-xl font-bold text-white">{selectedItem.title}</h1>
                                <p className="text-slate-400 text-sm font-mono">
                                    {selectedItem.id} | {new Date(selectedItem.timestamp).toLocaleString()}
                                </p>
                            </div>
                        </div>
                        <div
                            className="flex-1 overflow-y-auto pr-4 scrollbar-thin scrollbar-thumb-slate-700 prose prose-invert prose-slate max-w-none focus:outline-none focus:ring-2 focus:ring-cyan-500/30 rounded"
                            tabIndex={0}
                            aria-label="Report Content"
                        >
                            <ReactMarkdown>{getMockContent(selectedItem)}</ReactMarkdown>
                        </div>
                    </div>
                ) : (
                    <div className="h-full flex flex-col items-center justify-center text-slate-600">
                        <FileText size={48} className="mb-4 opacity-50" />
                        <p>Select an item from the feed to view details.</p>
                    </div>
                )}
            </GlassCard>
        </div>
    );
};

export default IntelFeed;
