from typing import Dict, Any, List
import os
import logging
from core.agents.agent_base import AgentBase
from core.agents.mixins.audit_mixin import AuditMixin

class AutoArchitectAgent(AgentBase, AuditMixin):
    """
    Scans the repository to generate a real-time 'Current State' architectural document.
    Ensures documentation never drifts from code.
    """

    def __init__(self, config=None, **kwargs):
        super().__init__(config, **kwargs)
        AuditMixin.__init__(self)
        self.output_path = "docs/architecture/current_state.md"

    async def execute(self, **kwargs) -> Dict[str, Any]:
        """
        Scans 'core/' and 'scripts/' to build a module map.
        """
        logging.info("AutoArchitectAgent starting codebase scan...")

        structure = self._scan_directory("core")
        script_structure = self._scan_directory("scripts")

        md_content = self._generate_markdown(structure, script_structure)

        os.makedirs(os.path.dirname(self.output_path), exist_ok=True)
        with open(self.output_path, 'w') as f:
            f.write(md_content)

        self.log_decision(
            activity_type="ArchitectureScan",
            details={"modules_found": len(structure)},
            outcome={"file_generated": self.output_path}
        )

        return {"status": "SUCCESS", "path": self.output_path}

    def _scan_directory(self, root_dir: str) -> Dict[str, List[str]]:
        tree = {}
        for root, dirs, files in os.walk(root_dir):
            if "__pycache__" in root:
                continue

            relative_root = os.path.relpath(root, os.getcwd())
            py_files = [f for f in files if f.endswith(".py") and f != "__init__.py"]

            if py_files:
                tree[relative_root] = py_files

        return tree

    def _generate_markdown(self, core_tree: Dict[str, List[str]], script_tree: Dict[str, List[str]]) -> str:
        md = "# System Architecture (Current State)\n\n"
        md += "Auto-generated by `AutoArchitectAgent`. Do not edit manually.\n\n"

        md += "## Core Modules\n"
        for folder, files in sorted(core_tree.items()):
            md += f"### `{folder}`\n"
            for f in sorted(files):
                md += f"- `{f}`\n"
            md += "\n"

        md += "## Scripts & Utilities\n"
        for folder, files in sorted(script_tree.items()):
            md += f"### `{folder}`\n"
            for f in sorted(files):
                md += f"- `{f}`\n"
            md += "\n"

        return md

    def get_skill_schema(self) -> Dict[str, Any]:
        return {
            "name": "AutoArchitectAgent",
            "description": "Generates live architectural documentation.",
            "skills": [
                {
                    "name": "scan_codebase",
                    "description": "Updates the current_state.md file.",
                    "parameters": {}
                }
            ]
        }
