import os
import json
import time
import random
from flask import Flask, send_from_directory, jsonify, request
from flask_cors import CORS

# Define the showcase directory relative to this script
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHOWCASE_DIR = os.path.join(BASE_DIR, 'showcase')
DATA_FILE = os.path.join(SHOWCASE_DIR, 'data', 'ui_data.json')

app = Flask(__name__, static_folder=SHOWCASE_DIR)
CORS(app)


@app.route('/')
def serve_index():
    """Serves the main index.html file."""
    return send_from_directory(SHOWCASE_DIR, 'index.html')


@app.route('/<path:path>')
def serve_static(path):
    """Serves static files from the showcase directory."""
    return send_from_directory(SHOWCASE_DIR, path)


@app.route('/api/state')
def get_state():
    """
    Retrieves the current system state.

    Simulates real-time updates by reading generated data and adding noise
    to system statistics.
    """
    # Simulate real-time updates by reading the generated data and adding some noise
    try:
        with open(DATA_FILE, 'r') as f:
            data = json.load(f)

        # Add dynamic elements
        data['system_stats']['cpu_usage'] = round(random.uniform(10, 60), 1)
        data['system_stats']['memory_usage'] = round(random.uniform(30, 80), 1)
        data['system_stats']['active_tasks'] = random.randint(1, 5)
        data['system_stats']['uptime'] = time.time() - data['generated_at']

        return jsonify(data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/files')
def get_files():
    """Retrieves the file structure of the repository."""
    try:
        with open(DATA_FILE, 'r') as f:
            data = json.load(f)
        return jsonify(data['files'])
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/agents')
def get_agents():
    """Retrieves the list of active agents."""
    try:
        with open(DATA_FILE, 'r') as f:
            data = json.load(f)
        return jsonify(data['agents'])
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/api/market_mayhem/latest')
def get_market_mayhem_latest():
    """Returns a mock latest market mayhem pulse."""
    mock_data = {
        "title": "Market Pulse: Dow Hits New Milestone",
        "date": "2026-03-13",
        "summary": "Weekly analysis covering the Sovereign AI & Crypto Supercycle theme. Sentiment is currently Euphoric.",
        "type": "MARKET_PULSE",
        "full_body": "<strong>Date:</strong> 2026-03-13<br><strong>Type:</strong> Market_Pulse<br><strong>Agent:</strong> MacroSage<br><h2>Executive Summary</h2>Weekly analysis covering the Sovereign AI & Crypto Supercycle theme. Sentiment is currently Euphoric.<h2>Analysis</h2>The market has been reacting to the Sovereign AI & Crypto Supercycle. We are seeing significant volatility in tech and energy sectors. Institutional flows suggest a rotation is underway.<h2>Key Metrics</h2><ul><li><strong>S&P 500:</strong> 5479</li><li><strong>VIX:</strong> 23.52</li><li><strong>10Y Treasury:</strong> 3.74%</li></ul><em>Generated by Adam v30.0 System Intelligence</em>",
        "sentiment_score": 50,
        "entities": {
            "tickers": [],
            "agents": [],
            "sovereigns": [],
            "keywords": ["AI", "Crypto", "Energy", "Tech", "Volatility"]
        },
        "provenance_hash": "6e94e45e7109f57159cd9210d3865431b0939a233cf1ecda50dbb59a51c9c0bd",
        "filename": "Market_Pulse_2026_03_13.html",
        "is_sourced": True,
        "metrics_json": "{}",
        "source_priority": 2,
        "conviction": 50,
        "critique": "Agent Sovereign_AI reviewed this intelligence. Verdict: HIGH_CONFIDENCE. Sentiment alignment: 50/100. Cross-reference with knowledge graph completed.",
        "quality": 100,
        "semantic_score": 88,
        "probability": 50,
        "outlook_score": 27
    }
    return jsonify(mock_data)


if __name__ == '__main__':
    print(f"Serving UI from {SHOWCASE_DIR}")
    host = os.environ.get('FLASK_HOST', '127.0.0.1')
    port = int(os.environ.get('FLASK_PORT', 5000))
    app.run(host=host, port=port, debug=False)
