# config/agents.yaml

market_sentiment_agent:
  data_sources:
    - financial_news_api
    - social_media_api
  sentiment_threshold: 0.6  # Example

macroeconomic_analysis_agent:
  data_sources:
    - government_statistical_agencies
  indicators:
    - GDP
    - inflation
    - unemployment

# ... other agents

# ... (previous entries)

geopolitical_risk_agent:
  # Add configuration if needed

industry_specialist_agent:
  sector: "technology"  # or "healthcare", "energy", etc.

data_verification_agent:
  # Add configuration if needed

lexica_agent:
  # Add configuration if needed

archive_manager_agent:
  archive_dir: "core/libraries_and_archives"
