analysis_modules:
  fundamental_analysis:
    # Configuration for the Fundamental Analysis Module
    valuation_method: dcf  # or comparables
    #... other module-specific configuration...

  technical_analysis:
    # Configuration for the Technical Analysis Module
    indicators:
    - rsi
    - macd
    #... other module-specific configuration...

  #... other analysis modules...

# Reporting Configuration
