# config/api_keys.yaml
    financial_news_api:
      bloomberg: YOUR_BLOOMBERG_API_KEY
      reuters: YOUR_REUTERS_API_KEY

    social_media_api:
        twitter:
            consumer_key: YOUR_TWITTER_CONSUMER_KEY
            consumer_secret: YOUR_TWITTER_CONSUMER_SECRET
            access_token: YOUR_TWITTER_ACCESS_TOKEN
            access_token_secret: YOUR_TWITTER_ACCESS_TOKEN_SECRET
        facebook: YOUR_FACEBOOK_API_KEY

    government_stats_api:
      bea_api_key: YOUR_BEA_API_KEY
      bls_api_key: YOUR_BLS_API_KEY

    market_data_api:
      iex_cloud: YOUR_IEX_CLOUD_API_KEY
      alpha_vantage: YOUR_ALPHA_VANTAGE_API_KEY
