# config/api_keys.yaml
financial_news_api:
  bloomberg:
  reuters:

social_media_api:
  twitter:
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
  facebook:

government_stats_api:
  bea_api_key:
  bls_api_key:

market_data_api:
  iex_cloud:
  alpha_vantage:
