#config/config.yaml

# Adam v17.0 Configuration File

# Knowledge Graph Configuration
knowledge_graph:
  path: data/knowledge_graph.json  # Path to the knowledge graph file

# API Configuration
api:
  host: 0.0.0.0  # Host for the API server (0.0.0.0 for all interfaces)
  port: 5000  # Port for the API server

# Agent Configuration
agents:
  market_sentiment_agent:
    # Configuration for the Market Sentiment Agent
    data_sources:
      - news_api
      - twitter_api
    sentiment_analysis_method: lexicon_based  # or machine_learning_based
    #... other agent-specific configuration...

  macroeconomic_analysis_agent:
    # Configuration for the Macroeconomic Analysis Agent
    data_sources:
      - fred_api
      - ecb_api
    macroeconomic_model: var  # or dsge
    #... other agent-specific configuration...

  geopolitical_risk_agent:
    # Configuration for the Geopolitical Risk Agent
    data_sources:
      - political_risk_api
      - news_api
    risk_assessment_method: quantitative  # or qualitative
    #... other agent-specific configuration...

  industry_specialist_agent:
    # Configuration for the Industry Specialist Agent
    industries:
      - technology
      - healthcare
      - finance
    data_sources:
      - industry_reports_api
      - company_filings_api
    #... other agent-specific configuration...

  fundamental_analyst_agent:
    # Configuration for the Fundamental Analyst Agent
    data_sources:
      - financial_statements_api
      - company_filings_api
    valuation_method: dcf  # or comparables
    #... other agent-specific configuration...

  technical_analyst_agent:
    # Configuration for the Technical Analyst Agent
    data_sources:
      - market_data_api
    indicators:
      - rsi
      - macd
      - bollinger_bands
    #... other agent-specific configuration...

  risk_assessment_agent:
    # Configuration for the Risk Assessment Agent
    risk_metrics:
      - var
      - credit_risk
      - liquidity_risk
    #... other agent-specific configuration...

  #... other agents...

# Data Sources Configuration
data_sources:
  news_api:
    api_key: YOUR_NEWS_API_KEY
    #... other data source-specific configuration...

  twitter_api:
    consumer_key: YOUR_CONSUMER_KEY
    consumer_secret: YOUR_CONSUMER_SECRET
    access_token: YOUR_ACCESS_TOKEN
    access_token_secret: YOUR_ACCESS_TOKEN_SECRET
    #... other data source-specific configuration...

  fred_api:
    api_key: YOUR_FRED_API_KEY
    #... other data source-specific configuration...

  ecb_api:
    api_key: YOUR_ECB_API_KEY
    #... other data source-specific configuration...

  political_risk_api:
    api_key: YOUR_POLITICAL_RISK_API_KEY
    #... other data source-specific configuration...

  industry_reports_api:
    api_key: YOUR_INDUSTRY_REPORTS_API_KEY
    #... other data source-specific configuration...

  company_filings_api:
    api_key: YOUR_COMPANY_FILINGS_API_KEY
    #... other data source-specific configuration...

  financial_statements_api:
    api_key: YOUR_FINANCIAL_STATEMENTS_API_KEY
    #... other data source-specific configuration...

  market_data_api:
    api_key: YOUR_MARKET_DATA_API_KEY
    #... other data source-specific configuration...

  #... other data sources...

# Analysis Modules Configuration
analysis_modules:
  fundamental_analysis:
    # Configuration for the Fundamental Analysis Module
    valuation_method: dcf  # or comparables
    #... other module-specific configuration...

  technical_analysis:
    # Configuration for the Technical Analysis Module
    indicators:
      - rsi
      - macd
    #... other module-specific configuration...

  #... other analysis modules...

# Reporting Configuration
reporting:
  format: json  # or csv, html, etc.
  #... other reporting configurations...

# Logging Configuration
logging:
  level: INFO  # or DEBUG, WARNING, ERROR, CRITICAL
  #... other logging configurations...

# Other Configurations
#...
