#config/config.yaml
# Adam v17.0 Configuration File

# This file has been deprecated.
# Configuration has been split into individual files within the config/ directory:
# - knowledge_graph.yaml
# - api.yaml
# - data_sources.yaml
# - analysis_modules.yaml
# - reporting.yaml
# - logging.yaml
#
# Please refer to these files for specific configurations.
