# core/config/data_sources.yaml

financial_news_api:
  api_keys:
    bloomberg: YOUR_BLOOMBERG_API_KEY
    reuters: YOUR_REUTERS_API_KEY
    #... (add API keys for other news sources)

social_media_api:
  api_keys:
    twitter:
      consumer_key: YOUR_TWITTER_CONSUMER_KEY
      consumer_secret: YOUR_TWITTER_CONSUMER_SECRET
      access_token: YOUR_TWITTER_ACCESS_TOKEN
      access_token_secret: YOUR_TWITTER_ACCESS_TOKEN_SECRET
    facebook: YOUR_FACEBOOK_API_KEY
    #... (add API keys for other social media platforms)

government_stats_api:
  api_keys:
    bea_api_key: YOUR_BEA_API_KEY
    bls_api_key: YOUR_BLS_API_KEY
    #... (add API keys for other government data sources)

market_data_api:
  api_keys:
    iex_cloud: YOUR_IEX_CLOUD_API_KEY
    alpha_vantage: YOUR_ALPHA_VANTAGE_API_KEY
    #... (add API keys for other market data providers)


# config/data_sources.yaml
risk_ratings:
  type: json
  path: data/risk_rating_mapping.json
market_baseline:
    type: json
    path: data/adam_market_baseline.json
# Add more data sources as needed
