# config/data_sources.yaml

# --- Local Data Files ---
risk_ratings:
  type: json
  path: data/risk_rating_mapping.json

market_baseline:
  type: json
  path: data/adam_market_baseline.json

knowledge_base:
  type: json
  path: data/knowledge_base.json

processed_data: # Example of a CSV file
  type: csv
  path: data/processed_data.csv

deal_template:
  type: json
  path: data/deal_template.json

dcf_valuation_template:
  type: json
  path: data/dcf_valuation_template.json

dcf_model_template: #Another CSV
    type: csv
    path: data/dcf_model_template.csv

ev_model_template: #Another CSV
    type: csv
    path: data/ev_model_template.csv

example_user_portfolio:
    type: json
    path: data/example_user_portfolio.json

example_user_profile:
    type: json
    path: data/example_user_profile.json

global_risk_appetite:
    type: csv
    path: data/global_risk_appetite_barometer_20250224.csv

adam_core_data:
  type: json
  path: data/adam_core_data.json

knowledge_graph:
    type: json
    path: data/knowledge_graph.json

# --- External Data Sources (APIs) ---
#   These entries define the *names* of the data sources.
#   The actual API keys and connection details should be handled
#   SEPARATELY, for security reasons (e.g., in environment variables
#   or a dedicated secrets management system).

financial_news_api:
  type: api
  provider: bloomberg, reuters # List supported providers

social_media_api:
  type: api
  provider: twitter, facebook

government_stats_api:
  type: api
  provider: bea, bls

market_data_api:
  type: api
  provider: iex_cloud, alpha_vantage

# --- Database Example (Future) ---
# database:
#   type: database
#   provider: postgresql  # Or mysql, sqlite, etc.
#   connection_string:  # Placeholder - DO NOT put credentials here!
