data_sources:
  news_api:
    api_key:
    #... other data source-specific configuration...

  twitter_api:
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
    #... other data source-specific configuration...

  fred_api:
    api_key:
    #... other data source-specific configuration...

  ecb_api:
    api_key:
    #... other data source-specific configuration...

  political_risk_api:
    api_key:
    #... other data source-specific configuration...

  industry_reports_api:
    api_key:
    #... other data source-specific configuration...

  company_filings_api:
    api_key:
    #... other data source-specific configuration...

  financial_statements_api:
    api_key:
    #... other data source-specific configuration...

  market_data_api:
    api_key:
    #... other data source-specific configuration...

  #... other data sources...

# Analysis Modules Configuration
