# config/errors.yaml

  errors:
    DataNotFoundError:
      code: 101
      message: "The requested data could not be found."
    AgentNotFoundError:
      code: 102
      message: "The requested agent is not registered."
    InvalidInputError:
      code: 103
      message: "The input provided is invalid or could not be processed."
    ConfigurationError:
      code: 104
      message: "A configuration error occurred."
    FileReadError:
      code: 105
      message: "An error occurred while reading a file."
    # Add other error codes as needed
