errors:
  DATA_NOT_FOUND:
    code: 101
    message: "Requested data not found."
  INVALID_INPUT:
    code: 102
    message: "Invalid input format."
  AGENT_NOT_FOUND:
    code: 103
    message: "Requested agent not found."
  # ... more error codes ...
