# core/config/report_layout.yaml

# General Report Settings
report_style: formal  # or "informal", "detailed", "summary"

# Company Report Settings
company_report:
  sections:
    - company_overview
    - financial_summary
    - fundamental_analysis
    - technical_analysis
    - risk_assessment
    - investment_thesis
  financial_summary:
    metrics:
      - revenue
      - earnings_per_share
      - debt_to_equity_ratio
  fundamental_analysis:
    valuation_models:
      - dcf
      - comparable_company_analysis
  risk_assessment:
    risk_factors:
      - market_risk
      - credit_risk
      - liquidity_risk

# Industry Report Settings
industry_report:
  sections:
    - industry_overview
    - key_trends
    - competitive_landscape
    - growth_drivers
    - risks_and_challenges
  key_trends:
    - trend_1
    - trend_2
    - trend_3
  competitive_landscape:
    companies:
      - company_a
      - company_b
      - company_c
