# config/settings.yaml

# System Settings
system:
  name: "Adam v19.0"
  log_level: "INFO"
  data_dir: "data/"
  output_dir: "outputs/"

# Agent Configurations
agents:
  market_sentiment_agent:
    enabled: true
    data_sources:
      - "news_api"
      - "social_media_api"
  fundamental_analysis_agent:
    enabled: true
    valuation_model: "DCF"
  # ... other agent configurations

# Simulation Configurations
simulations:
  credit_rating_assessment:
    enabled: true
    default_agents:
      - "fundamental_analysis_agent"
      - "risk_assessment_agent"
  # ... other simulation configurations

# Plugin Configurations
plugins:
  example_plugin:
    enabled: true
    setting1: "value1"
    setting2: "value2"
  # ... other plugin configurations
