import logging
import random
from typing import Dict, Any, List

# Standard import
from core.v30_architecture.python_intelligence.agents.base_agent import BaseAgent

logger = logging.getLogger("ReviewerAgent")

class ReviewerAgent(BaseAgent):
    """
    Critiques reports generated by other agents for consistency, quality, and risk.
    """
    def __init__(self):
        super().__init__("Reviewer-V30", "quality_control")

    def review(self, report_type: str, content: Dict[str, Any], technical_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Reviews a report.

        Args:
            report_type: 'Market_Pulse', 'House_View', etc.
            content: The generated content (title, summary, body).
            technical_data: The quantitative data backing the report (price, signal, conviction).

        Returns:
            Dict containing 'critique', 'quality_score' (0-100), 'flags'.
        """
        critique = []
        flags = []
        score = 100

        # 1. Consistency Check: Sentiment vs Signal
        # Assuming technical_data['signal'] is BULLISH/BEARISH/NEUTRAL
        # And content['summary'] contains keywords

        signal = technical_data.get('signal', 'NEUTRAL')
        summary_lower = content.get('summary', '').lower()

        is_summary_bullish = any(x in summary_lower for x in ['bullish', 'growth', 'rally', 'surge', 'optimism'])
        is_summary_bearish = any(x in summary_lower for x in ['bearish', 'correction', 'decline', 'crash', 'recession'])

        if signal == 'BULLISH' and is_summary_bearish:
            critique.append("CONFLICT: Technical signal is BULLISH but narrative appears BEARISH.")
            score -= 20
            flags.append("sentiment_mismatch")
        elif signal == 'BEARISH' and is_summary_bullish:
            critique.append("CONFLICT: Technical signal is BEARISH but narrative appears BULLISH.")
            score -= 20
            flags.append("sentiment_mismatch")
        else:
            critique.append("Narrative aligns with technical signals.")

        # 2. Conviction Check
        conviction = technical_data.get('conviction', 50)
        if conviction < 30:
            critique.append("Low technical conviction suggests high uncertainty.")
            score -= 10
        elif conviction > 80:
            critique.append("High technical conviction supports strong assertions.")

        # 3. Data Integrity (Simulated)
        if technical_data.get('price') is None:
             critique.append("CRITICAL: Missing price data.")
             score -= 50
             flags.append("missing_data")

        # 4. Final Polish
        if score > 90:
            critique.append("Report meets highest quality standards.")
        elif score > 70:
            critique.append("Report is acceptable but has minor inconsistencies.")
        else:
            critique.append("Report requires significant revision.")

        return {
            "critique": " ".join(critique),
            "quality_score": max(0, score),
            "flags": flags,
            "reviewer": self.name
        }
