import os
import json
import random
import datetime
import pandas as pd
from datetime import timedelta

# Import Agents
from core.data.historical_loader import load_data
from core.v30_architecture.python_intelligence.agents.quantitative_analyst import QuantitativeAnalyst
from core.v30_architecture.python_intelligence.agents.reviewer_agent import ReviewerAgent

# Configuration
OUTPUT_DIR = "core/libraries_and_archives/generated_content"
PORTFOLIO_HISTORY_FILE = "showcase/data/portfolio_history.json"
START_DATE = datetime.date(2025, 1, 1)
END_DATE = datetime.date(2026, 3, 30)

# Load Historical Data (Global)
HISTORICAL_DATA = load_data()

def get_market_data_for_date(date_str):
    """Returns a DataFrame slice up to the given date for SPY."""
    if "SPY" not in HISTORICAL_DATA:
        return pd.DataFrame()

    spy_data = HISTORICAL_DATA["SPY"] # This is likely a dict of date -> {OHLC} if loaded from JSON
    # Wait, load_data returns {date: {ticker: {...}}}

    # We need to reconstruct a DataFrame for the Quant Analyst
    # Filter dates <= date_str

    records = []
    for d, tickers in HISTORICAL_DATA.items():
        if d <= date_str and "SPY" in tickers:
            row = tickers["SPY"]
            row["Date"] = d
            records.append(row)

    df = pd.DataFrame(records)
    if not df.empty:
        df["Date"] = pd.to_datetime(df["Date"])
        df = df.set_index("Date").sort_index()

    return df

def generate_markdown(date, type, title, summary, content, meta):
    filename = f"{type}_{date.strftime('%Y_%m_%d')}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)

    conviction_color = "green" if meta['conviction'] > 60 else "red" if meta['conviction'] < 40 else "yellow"

    md_content = f"""# {title}

**Date:** {date.strftime('%Y-%m-%d')}
**Type:** {type}
**Agent:** {meta.get('agent', 'System')}
**Conviction:** <span style="color:{conviction_color}">{meta.get('conviction', 50)}/100</span>

## Executive Summary
{summary}

## Analysis
{content}

## Technical Review
**Signal:** {meta.get('signal', 'NEUTRAL')}
**Critique:** {meta.get('critique', 'No review available.')}
**Quality Score:** {meta.get('quality_score', 0)}/100

## Key Metrics
- **Price:** ${meta.get('price', 0)}
- **RSI:** {meta.get('rsi', 0)}
- **VIX:** {meta.get('vix', 'N/A')}

*Generated by Adam v30.0 Agentic Network*
"""
    with open(filepath, "w") as f:
        f.write(md_content)
    return filepath

def generate_agentic_content():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    quant_agent = QuantitativeAnalyst()
    reviewer_agent = ReviewerAgent()

    current_date = START_DATE

    print("Starting Agentic Content Generation...")

    while current_date <= END_DATE:
        date_str = current_date.strftime("%Y-%m-%d")

        # 1. Get Data
        # For future dates (beyond real history), we might need simulation or just hold last value
        # For now, let's assume HISTORICAL_DATA covers up to "today" and the rest is simulated logic
        # But wait, the requirement is "Reliable historic data where available".
        # If date is in HISTORICAL_DATA, use it.

        is_real_data = date_str in HISTORICAL_DATA

        market_df = get_market_data_for_date(date_str)

        # 2. Quant Analysis
        quant_result = {}
        if not market_df.empty and len(market_df) > 20:
            quant_result = quant_agent.analyze_historical("SPY", market_df)

        # Fallback for future/missing data (Simulate)
        if "error" in quant_result or not quant_result:
            # Simulate a trend based on previous logic or random walk
            quant_result = {
                "signal": random.choice(["BULLISH", "BEARISH", "NEUTRAL"]),
                "conviction": random.randint(40, 90),
                "price": 500.0 + random.uniform(-50, 50),
                "rsi": 50.0
            }

        # 3. Generate Narrative (Fundamental/Macro) based on Signal
        signal = quant_result.get("signal", "NEUTRAL")

        headlines = {
            "BULLISH": ["Market Rallies", "Tech Leads Gains", "Breakout Confirmed", "Sentiment Improves"],
            "BEARISH": ["Sell-off Intensifies", "Support Broken", "Risk-Off Sentiment", "Correction Deepens"],
            "NEUTRAL": ["Market Consolidates", "Trading Range Continues", "Mixed Signals", "Awaiting Catalyst"]
        }

        title = f"Market Pulse: {random.choice(headlines[signal])}"
        summary = f"Agents detect {signal.lower()} conditions with conviction {quant_result['conviction']}."
        content = f"Technical indicators suggest {signal} momentum. RSI is at {quant_result['rsi']}."

        # 4. Review
        review_result = reviewer_agent.review("Market_Pulse", {"summary": summary}, quant_result)

        # 5. Output
        # Only generate weekly on Fridays
        if current_date.weekday() == 4:
            meta = {
                "agent": "QuantitativeAnalyst",
                "conviction": quant_result['conviction'],
                "signal": signal,
                "price": quant_result['price'],
                "rsi": quant_result['rsi'],
                "critique": review_result['critique'],
                "quality_score": review_result['quality_score'],
                "vix": "N/A" # Could fetch if available
            }
            generate_markdown(current_date, "Market_Pulse", title, summary, content, meta)

        current_date += timedelta(days=1)

    print("Agentic Content Generation Complete.")

if __name__ == "__main__":
    generate_agentic_content()
