import json
import os
import random
import datetime

DATA_DIR = 'showcase/data'
MODELS_DIR = os.path.join(DATA_DIR, 'models')
HISTORY_DIR = os.path.join(DATA_DIR, 'history')
NEWSLETTERS_DIR = os.path.join(DATA_DIR, 'newsletters')
BRIEFINGS_DIR = os.path.join(DATA_DIR, 'briefings')
SIMULATIONS_DIR = os.path.join(DATA_DIR, 'simulations')
DEEP_DIVES_DIR = os.path.join(DATA_DIR, 'deep_dives')
CREDIT_REPORTS_DIR = os.path.join(DATA_DIR, 'credit_reports')
EQUITY_REPORTS_DIR = os.path.join(DATA_DIR, 'equity_reports')

# Create directories if not exist
for d in [MODELS_DIR, HISTORY_DIR, NEWSLETTERS_DIR, BRIEFINGS_DIR, SIMULATIONS_DIR, DEEP_DIVES_DIR, CREDIT_REPORTS_DIR, EQUITY_REPORTS_DIR]:
    if not os.path.exists(d):
        os.makedirs(d)

def load_market_data():
    path = os.path.join(DATA_DIR, 'sp500_market_data.json')
    if os.path.exists(path):
        with open(path, 'r') as f:
            return json.load(f)
    return []

def generate_dcf(ticker, price):
    wacc = random.uniform(0.08, 0.12)
    growth = random.uniform(0.02, 0.10)
    tv_growth = 0.025
    fcf = price * random.uniform(0.03, 0.08) # Simplistic FCF proxy

    projections = []
    current_fcf = fcf
    for i in range(1, 6):
        current_fcf *= (1 + growth)
        projections.append(round(current_fcf, 2))

    terminal_value = (current_fcf * (1 + tv_growth)) / (wacc - tv_growth)

    return {
        "ticker": ticker,
        "type": "DCF",
        "wacc": round(wacc, 4),
        "growth_rate": round(growth, 4),
        "terminal_growth": tv_growth,
        "fcf_projections": projections,
        "terminal_value": round(terminal_value, 2),
        "current_price": price,
        "implied_value": round(sum([f / ((1+wacc)**(i+1)) for i, f in enumerate(projections)]) + (terminal_value / ((1+wacc)**5)), 2)
    }

def generate_ev_model(ticker, market_cap):
    # market_cap is strictly numeric? check source.
    # In sp500_market_data.json, market_cap is string like "2.5T"
    val = float(market_cap.replace('T', '')) * 1000 # Billions
    debt = val * random.uniform(0.1, 0.4)
    cash = val * random.uniform(0.05, 0.2)

    return {
        "ticker": ticker,
        "type": "EV",
        "market_cap": val,
        "total_debt": round(debt, 2),
        "cash_and_equivalents": round(cash, 2),
        "enterprise_value": round(val + debt - cash, 2),
        "ebitda": round((val + debt - cash) / random.uniform(10, 25), 2)
    }

def generate_html_report(ticker, name, report_type, year="2026"):
    title = f"{name} ({ticker}) - {report_type} {year}"
    content = f"""
    <html>
    <head>
        <title>{title}</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; padding: 40px; background: #fff; color: #333; }}
            h1 {{ color: #0078d7; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            .metric {{ display: inline-block; width: 150px; margin: 10px; padding: 10px; background: #f9f9f9; border-radius: 5px; text-align: center; }}
            .metric-val {{ font-size: 24px; font-weight: bold; color: #333; }}
            .metric-label {{ font-size: 12px; color: #888; }}
            .section {{ margin-top: 30px; }}
            p {{ line-height: 1.6; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        <div class="metrics">
            <div class="metric"><div class="metric-val">{random.choice(['Buy', 'Hold', 'Sell'])}</div><div class="metric-label">Rating</div></div>
            <div class="metric"><div class="metric-val">${random.randint(100, 3000)}</div><div class="metric-label">Target Price</div></div>
            <div class="metric"><div class="metric-val">{random.randint(1, 99)}%</div><div class="metric-label">Upside</div></div>
        </div>

        <div class="section">
            <h3>Executive Summary</h3>
            <p>{name} continues to demonstrate strong market resilience. Our proprietary {report_type} model indicates robust fundamentals despite macroeconomic headwinds. Key catalysts include product innovation in AI and strategic cost optimization.</p>
        </div>

        <div class="section">
            <h3>Valuation Methodology</h3>
            <p>We utilize a blended approach of DCF (50%) and EV/EBITDA multiples (50%). Our WACC assumption is {random.uniform(8.0, 11.0):.1f}% based on a beta of {random.uniform(0.8, 1.5):.2f}.</p>
        </div>

        <div class="section">
            <h3>Risk Factors</h3>
            <ul>
                <li>Regulatory scrutiny in key markets.</li>
                <li>Supply chain disruptions affecting gross margins.</li>
                <li>Intensifying competition from emerging players.</li>
            </ul>
        </div>

        <div style="margin-top: 50px; font-size: 12px; color: #aaa; text-align: center;">
            Generated by Office Nexus Analytical Engine | {datetime.date.today()}
        </div>
    </body>
    </html>
    """
    return content

def generate_newsletter():
    return """
    <html>
    <head><title>Market Mayhem: Feb 2026</title></head>
    <body style="font-family: Georgia, serif; padding: 40px; max-width: 800px; margin: auto; background: #fdfdfd;">
        <h1 style="font-size: 48px; text-align: center; border-bottom: 4px double #000; padding-bottom: 20px;">MARKET MAYHEM</h1>
        <div style="text-align: center; font-style: italic; margin-bottom: 40px;">Vol. 42 | February 2026 | The "AI Winter" Edition</div>

        <h2 style="font-family: Arial, sans-serif;">The Great Bifurcation Continues</h2>
        <p>As the S&P 500 tests new highs, the divergence between the "Magnificent 7" and the rest of the market has reached historic levels. Simulation models predict a mean reversion event within Q2 2026 with a probability of 68%.</p>

        <h3 style="font-family: Arial, sans-serif;">Sector Watch: Semiconductors</h3>
        <p>Inventory glut concerns are mounting. Channel checks suggest a 15% reduction in orders from hyperscalers. Is the capex cycle peaking?</p>

        <div style="background: #eee; padding: 20px; margin: 30px 0; border-left: 5px solid #d32f2f;">
            <strong>Analyst Note:</strong> "Volatility is the price of admission for the next decade of returns." - <em>Chief Strategist</em>
        </div>
    </body>
    </html>
    """

def generate_briefing():
    return """
    <html>
    <head><title>Morning Call: Feb 19, 2026</title></head>
    <body style="font-family: 'Segoe UI', sans-serif; padding: 20px; background: #1e1e1e; color: #fff;">
        <h2 style="border-bottom: 1px solid #555; padding-bottom: 10px;">☀️ Morning Call</h2>
        <div style="font-size: 12px; color: #aaa; margin-bottom: 20px;">Thursday, Feb 19, 2026</div>

        <div style="margin-bottom: 15px;">
            <span style="background: #4caf50; padding: 2px 6px; border-radius: 3px; font-size: 11px;">MARKETS</span>
            <strong>Futures Up 0.5%</strong> on strong jobless claims data.
        </div>

        <div style="margin-bottom: 15px;">
            <span style="background: #2196f3; padding: 2px 6px; border-radius: 3px; font-size: 11px;">TECH</span>
            <strong>NVIDIA</strong> announces new Blackwell-Ultra chip, promising 3x efficiency gains.
        </div>

        <div style="margin-bottom: 15px;">
            <span style="background: #f44336; padding: 2px 6px; border-radius: 3px; font-size: 11px;">RISK</span>
            Geopolitical tensions in the South China Sea elevate shipping insurance premiums by 20%.
        </div>
    </body>
    </html>
    """

def main():
    market_data = load_market_data()
    print(f"Loaded {len(market_data)} tickers.")

    for item in market_data:
        ticker = item['ticker']
        name = item['name']

        # Models
        dcf = generate_dcf(ticker, item['current_price'])
        with open(os.path.join(MODELS_DIR, f"{ticker}_DCF.json"), 'w') as f:
            json.dump(dcf, f, indent=2)

        ev = generate_ev_model(ticker, item['market_cap'])
        with open(os.path.join(MODELS_DIR, f"{ticker}_EV.json"), 'w') as f:
            json.dump(ev, f, indent=2)

        # Reports
        eq_html = generate_html_report(ticker, name, "Equity Research Report")
        with open(os.path.join(EQUITY_REPORTS_DIR, f"{ticker}_Equity_Report_2026.html"), 'w') as f:
            f.write(eq_html)

        cr_html = generate_html_report(ticker, name, "Credit Memo")
        with open(os.path.join(CREDIT_REPORTS_DIR, f"{ticker}_Credit_Memo_2026.html"), 'w') as f:
            f.write(cr_html)

        # History
        hist_html = generate_html_report(ticker, name, "Annual Review", "2025")
        with open(os.path.join(HISTORY_DIR, f"{ticker}_2025_Review.html"), 'w') as f:
            f.write(hist_html)

    # Global Artifacts
    with open(os.path.join(NEWSLETTERS_DIR, "Market_Mayhem_Feb_2026.html"), 'w') as f:
        f.write(generate_newsletter())

    with open(os.path.join(BRIEFINGS_DIR, "Morning_Call_Feb_19_2026.html"), 'w') as f:
        f.write(generate_briefing())

    # Simulation
    sim_data = {
        "scenario": "AI Bubble Burst",
        "probability": 0.35,
        "impact": "High",
        "affected_sectors": ["Technology", "Semiconductors"],
        "trigger_event": "Regulatory crackdown on LLM usage."
    }
    with open(os.path.join(SIMULATIONS_DIR, "Crash_Scenario_2026.json"), 'w') as f:
        json.dump(sim_data, f, indent=2)

    # Deep Dive
    deep_html = generate_html_report("SYSTEM", "Global Market", "Deep Dive: AI Bubble Analysis")
    with open(os.path.join(DEEP_DIVES_DIR, "AI_Bubble_Analysis.html"), 'w') as f:
        f.write(deep_html)

    print("Comprehensive artifacts generated.")

if __name__ == "__main__":
    main()
