import os
import json
import random
import datetime
from datetime import timedelta

# Configuration
OUTPUT_DIR = "core/libraries_and_archives/generated_content"
PORTFOLIO_HISTORY_FILE = "showcase/data/portfolio_history.json"
START_DATE = datetime.date(2025, 1, 1)
END_DATE = datetime.date(2026, 3, 30)

# Narrative Arcs
NARRATIVES = [
    {"start": datetime.date(2025, 1, 1), "end": datetime.date(2025, 3, 31), "theme": "Tech Correction", "sentiment": "Bearish", "market_trend": -0.05},
    {"start": datetime.date(2025, 4, 1), "end": datetime.date(2025, 6, 30), "theme": "AI Application Boom", "sentiment": "Bullish", "market_trend": 0.10},
    {"start": datetime.date(2025, 7, 1), "end": datetime.date(2025, 9, 30), "theme": "Energy Crisis & Geopolitics", "sentiment": "Volatile", "market_trend": -0.02},
    {"start": datetime.date(2025, 10, 1), "end": datetime.date(2025, 12, 31), "theme": "Rate Cuts & Holiday Rally", "sentiment": "Bullish", "market_trend": 0.15},
    {"start": datetime.date(2026, 1, 1), "end": datetime.date(2026, 3, 30), "theme": "Sovereign AI & Crypto Supercycle", "sentiment": "Euphoric", "market_trend": 0.20},
]

HEADLINES = {
    "Bearish": [
        "Tech Stocks Tumble on Rate Fears",
        "Inflation Data Comes in Hot",
        "Fed Signals Higher for Longer",
        "Supply Chain Woes Return",
        "Consumer Confidence Hits Lows",
        "AI Bubble Bursts?",
        "Energy Prices Spike",
        "Geopolitical Tensions Escalate"
    ],
    "Bullish": [
        "AI Adoption Accelerates",
        "Fed Pivots to Cuts",
        "Tech Earnings Crush Estimates",
        "Productivity Boom Confirmed",
        "Crypto Hits All-Time Highs",
        "Sovereign Wealth Funds Buy Tech",
        "Soft Landing Achieved",
        "Consumer Spending Robust"
    ],
    "Volatile": [
        "Market Swings Wildly on Fed Speak",
        "VIX Spikes Amid Uncertainty",
        "Sector Rotation Confuses Traders",
        "Oil Prices Whiplash Markets",
        "Earnings Mixed, Guidance Unclear",
        "Bond Yields Invert Further"
    ],
    "Euphoric": [
        "Market Melts Up",
        "Bitcoin Smashes Resistance",
        "AI Stocks Go Parabolic",
        "Global Growth Synchronizes",
        "The Roaring 20s Are Back",
        "Dow Hits New Milestone"
    ]
}

AGENTS = ["MarketScanner", "RiskGuardian", "FundamentalAnalyst", "TechnoKing_v9", "MacroSage"]

def get_narrative(date):
    for n in NARRATIVES:
        if n["start"] <= date <= n["end"]:
            return n
    return NARRATIVES[-1]

def generate_markdown(date, type, title, summary, content):
    filename = f"{type}_{date.strftime('%Y_%m_%d')}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)

    md_content = f"""# {title}

**Date:** {date.strftime('%Y-%m-%d')}
**Type:** {type}
**Agent:** {random.choice(AGENTS)}

## Executive Summary
{summary}

## Analysis
{content}

## Key Metrics
- **S&P 500:** {random.randint(4000, 6000)}
- **VIX:** {random.uniform(10, 35):.2f}
- **10Y Treasury:** {random.uniform(3.5, 5.0):.2f}%

*Generated by Adam v30.0 System Intelligence*
"""
    with open(filepath, "w") as f:
        f.write(md_content)
    return filepath

def generate_portfolio_history():
    history = []
    current_date = START_DATE

    # Initial Values
    portfolios = {
        "aggressive": {"value": 100000, "holdings": {"NVDA": 0.4, "BTC": 0.3, "PLTR": 0.2, "CASH": 0.1}},
        "balanced": {"value": 100000, "holdings": {"SPY": 0.5, "AGG": 0.3, "GLD": 0.1, "CASH": 0.1}},
        "defensive": {"value": 100000, "holdings": {"SHV": 0.6, "XLU": 0.2, "JNJ": 0.1, "CASH": 0.1}}
    }

    while current_date <= END_DATE:
        narrative = get_narrative(current_date)
        daily_trend = narrative["market_trend"] / 90 # Approximate daily trend
        volatility = 0.01 if narrative["sentiment"] != "Volatile" else 0.02

        day_stats = {"date": current_date.strftime("%Y-%m-%d"), "portfolios": {}}

        for name, p in portfolios.items():
            # Apply daily change
            noise = random.normalvariate(0, volatility)
            beta = 1.5 if name == "aggressive" else (1.0 if name == "balanced" else 0.5)

            # Crypto/AI specific boost in Euphoric
            if narrative["theme"] == "Sovereign AI & Crypto Supercycle" and name == "aggressive":
                beta = 2.0

            daily_return = daily_trend * beta + noise
            p["value"] *= (1 + daily_return)

            day_stats["portfolios"][name] = {
                "value": round(p["value"], 2),
                "daily_return": f"{daily_return*100:.2f}%",
                "narrative": narrative["theme"]
            }

        history.append(day_stats)
        current_date += timedelta(days=1)

    os.makedirs(os.path.dirname(PORTFOLIO_HISTORY_FILE), exist_ok=True)
    with open(PORTFOLIO_HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=2)
    print(f"Generated portfolio history: {PORTFOLIO_HISTORY_FILE}")

def main():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    current_date = START_DATE
    while current_date <= END_DATE:
        narrative = get_narrative(current_date)
        sentiment = narrative["sentiment"]
        theme = narrative["theme"]

        # Weekly: Market Pulse (Fridays)
        if current_date.weekday() == 4:
            title = f"Market Pulse: {random.choice(HEADLINES[sentiment])}"
            summary = f"Weekly analysis covering the {theme} theme. Sentiment is currently {sentiment}."
            content = f"The market has been reacting to the {theme}. We are seeing significant volatility in tech and energy sectors. Institutional flows suggest a rotation is underway."
            generate_markdown(current_date, "Market_Pulse", title, summary, content)

        # Monthly: House View (1st of month)
        if current_date.day == 1:
            title = f"House View: {theme} Outlook"
            summary = f"Strategic allocation update for {current_date.strftime('%B %Y')}. The {theme} remains the dominant macro driver."
            content = f"We recommend adjusting exposure based on the {theme}. The {sentiment} environment suggests caution/opportunity."
            generate_markdown(current_date, "House_View", title, summary, content)

        # Daily Briefing (Random ~30% chance)
        if random.random() < 0.3 and current_date.weekday() < 5:
             title = f"Daily Briefing: {theme} Update"
             summary = f"Quick update on {theme} and market movements."
             content = "Markets are moving fast. Key levels to watch: S&P 500 support at 4500, resistance at 5200."
             generate_markdown(current_date, "Daily_Briefing", title, summary, content)

        current_date += timedelta(days=1)

    print(f"Generated content in {OUTPUT_DIR}")
    generate_portfolio_history()

if __name__ == "__main__":
    main()
