import os
import json
import re
from pathlib import Path

# Configuration
PROMPT_LIB_DIR = "prompt_library"
CORE_PROMPTING_DIR = "core/prompting"
OUTPUT_FILE = "showcase/js/mock_prompts.js"

def parse_frontmatter(content):
    """Parses YAML frontmatter from markdown files."""
    frontmatter = {}
    body = content
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            try:
                # Basic YAML parsing (key: value)
                yaml_block = parts[1]
                for line in yaml_block.split("\n"):
                    if ":" in line:
                        key, val = line.split(":", 1)
                        frontmatter[key.strip()] = val.strip().strip('"').strip("'")
                body = parts[2]
            except Exception as e:
                print(f"Error parsing frontmatter: {e}")
    return frontmatter, body.strip()

def scan_directory(directory):
    prompts = []
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".md") or file.endswith(".json"):
                filepath = os.path.join(root, file)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()

                    relative_path = os.path.relpath(filepath, start=".")
                    name = file
                    category = os.path.basename(root).upper()

                    # Metadata extraction
                    metadata = {}
                    body = content

                    if file.endswith(".md"):
                        frontmatter, body = parse_frontmatter(content)
                        metadata.update(frontmatter)
                        type_ = "MARKDOWN"
                    elif file.endswith(".json"):
                        try:
                            json_content = json.loads(content)
                            # Heuristic: if it looks like a prompt schema
                            if "template" in json_content or "system_prompt" in json_content:
                                metadata = json_content
                                body = json.dumps(json_content, indent=2)
                                type_ = "JSON_SCHEMA"
                            else:
                                continue # Skip non-prompt JSONs (like data files)
                        except:
                            continue

                    prompts.append({
                        "id": relative_path.replace("/", "_").replace(".", "_"),
                        "name": name,
                        "path": relative_path,
                        "category": category if category != "." else "ROOT",
                        "type": type_,
                        "content": body,
                        "metadata": metadata
                    })
                except Exception as e:
                    print(f"Skipping {filepath}: {e}")
    return prompts

def main():
    print(f"Scanning {PROMPT_LIB_DIR}...")
    lib_prompts = scan_directory(PROMPT_LIB_DIR)

    print(f"Scanning {CORE_PROMPTING_DIR}...")
    core_prompts = scan_directory(CORE_PROMPTING_DIR)

    all_prompts = lib_prompts + core_prompts

    print(f"Found {len(all_prompts)} prompts.")

    js_content = f"""// Generated by scripts/generate_mock_prompts.py
if (!window.MOCK_DATA) window.MOCK_DATA = {{}};
window.MOCK_DATA.prompts = {json.dumps(all_prompts, indent=2)};
"""

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"Successfully wrote {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
