#!/usr/bin/env python3
import sys
import os

# Ensure core module is in path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from core.future_state.engine import SingularityEngine, WorldState, Era
from core.future_state.entropy import ThermodynamicSystem
from core.future_state.governance import AlgocraticCouncil, PoliticalCompass
from core.future_state.ubc import EnergyMarket
from core.future_state.ops import ComputeSubstrate, AutonomousPipeline
from core.future_state.assumptions import SimulationAssumptions

def print_disclaimers():
    print("\n" + "!"*60)
    print("DISCLAIMER: SPECULATIVE SIMULATION TOOL")
    print("!"*60)
    print("This output is generated by a probabilistic model based on")
    print("technological and economic assumptions defined in")
    print("docs/DISCLAIMERS_AND_ASSUMPTIONS.md.")
    print("\nNOT FINANCIAL ADVICE. NOT PREDICTIVE ORACLE.")
    print("!"*60 + "\n")

def print_header(title):
    print(f"\n{'='*60}\n{title}\n{'='*60}")

def print_dashboard(engine):
    state = engine.state
    print_header(f"STRATEGIC DASHBOARD: YEAR {state.year}")

    print(f"ERA:                 {state.era.value}")
    print(f"SINGULARITY INDEX:   {state.singularity_index:.3f}")
    print("-" * 30)
    print(f"HUMAN GDP:           ${state.human_gdp:.2f} T")
    print(f"AI GDP:              ${state.ai_gdp:.2e} T")
    print("-" * 30)
    print(f"ALIGNMENT SCORE:     {state.alignment.get_risk_level()} (B: {state.alignment.benevolence:.2f})")
    print(f"CONSCIOUSNESS (Phi): {state.consciousness.phi_score:.4f}")
    print("-" * 30)
    print(f"POLITICAL AXIS:      Auth: {state.governance.political_compass.authority_score:.2f} | Substrate: {state.governance.political_compass.substrate_score:.2f}")
    print(f"COMPUTE SUBSTRATE:   {state.compute_substrate.type} ({state.compute_substrate.total_flops:.1e} FLOPS)")
    print(f"RECURSION DEPTH:     {state.ops_pipeline.recursion_depth}")
    print(f"SOVEREIGN LAB VAL:   ${state.corporate_sector.sovereign_labs_valuation:.1f} B")

def main():
    print_disclaimers()

    # Initialize components
    thermo_sys = ThermodynamicSystem(total_energy_joules=1e18)
    gov = AlgocraticCouncil()
    energy_mkt = EnergyMarket()

    # Create World State
    world = WorldState(
        year=2025,
        global_entropy=thermo_sys,
        governance=gov,
        energy_market=energy_mkt
    )

    # Initialize Engine with Assumptions
    assumptions = SimulationAssumptions()
    print(f"Initializing Engine with Assumptions:")
    print(f" - Moore's Law Doubling: {assumptions.MOORES_LAW_DOUBLING_MONTHS} months")
    print(f" - Initial Human GDP: ${assumptions.INITIAL_HUMAN_GDP} T")

    engine = SingularityEngine(state=world, assumptions=assumptions)

    # Run Simulation
    print("\n--- TIMELINE EXECUTION ---")
    logs = engine.run_simulation(end_year=2125)

    # Print notable events (filtered)
    for entry in logs:
        if "EVENT" in entry or "ERA SHIFT" in entry or "TRIGGERED" in entry:
            print(entry)
        # Print a snapshot every 25 years
        try:
            year_str = entry.split()[1]
            if year_str.isdigit():
                year = int(year_str)
                if year % 25 == 0:
                    print(f"--- SNAPSHOT {year} ---")
        except:
            pass

    # Final Dashboard
    print_dashboard(engine)

if __name__ == "__main__":
    main()
